### ISSUE TITLE
Error, undefined function: msg_queue_exists

### ISSUE THREAD

**Issue by IngwiePhoenix** [hfcorriez/php-childprocess#1]
Hey.

I looked at the code and did not find this function in your code either. Which extension or such do I have to install to get the listening functionality?

Kind regards, Ingwie.

**Comment by hfcorriez** [comment]
This function is required by sysvmsg enabled when PHP is compiling.  

http://php.net/manual/en/sem.installation.php  

---

hfcorriez

在 2015年4月13日 星期一，03:20，Ingwie Phoenix 写道：

**Comment by IngwiePhoenix** [comment]
Okay thanks! That fixed it.
