### ISSUE TITLE
Messaging not working

### ISSUE THREAD

**Issue by IngwiePhoenix** [hfcorriez/php-childprocess#2]
I am trying to send messages back and forth - here is a snippet of my code:

``` php
            $manager = new \Pagon\ChildProcess();
            $manager->listen();
            $out = "";
            $child = $manager->parallel(function($p){
                try{
                    $p->on("message", function($ch){
                        echo "Got chunk...\n";
                    });
                    $p->on("exit", function(){
                        echo "Child is exiting...\n";
                    });
                    $p->listen();
                    echo "Meep!\n";
                    ob_start();
                    echo "o.o!\n";
                    $res = ob_get_contents();
                    ob_end_clean();
                    $p->send($res);
                } catch(\Exception $e) {
                    echo "Child exception\n";
                }
                sleep(2);
            }, false);
            $child->on("message", function($ch) use($out){
                echo "Got message; $ch\n";
                $out .= $ch;
            });
            $child->on("exit", function(){
                echo "Exiting...\n";
            });
            $child->on("listen", function(){
                echo "\$child: listen\n";
            });
            #$child->listen();
            $child->wait();
            return $res->end($out);
```

But neither the listen or message event is triggered... What am I doing wrong?

**Comment by hfcorriez** [comment]
I will check this at night. Are u use it under Web mode? What’s the mean of res->end()?

---

hfcorriez

在 2015年4月13日 星期一，16:45，Ingwie Phoenix 写道：

**Comment by IngwiePhoenix** [comment]
I am using a self-structured socket server system based on Workerman - its a bit larger. The code - not the most current one - is here: http://git.ingwie.me/ingwie/bird3/tree/master/php-lib http://git.ingwie.me/ingwie/bird3/tree/master/php-lib

YiiApp.php has the code that is responsible for sending back a request. I want to use php-childprocess in order to get rid of needing to restart the current worker (YiiApp::stop()). The request is sent back and forth using Hprose ( https://github https://github/.com/hprose ) and the code responsible for that is here: http://git.ingwie.me/ingwie/bird3/blob/master/node-lib/php_handler.js http://git.ingwie.me/ingwie/bird3/blob/master/node-lib/php_handler.js

**Comment by hfcorriez** [comment]
I see. I am not in my office, I will check when I arrived my office!

**Comment by IngwiePhoenix** [comment]
Okay! :)

**Comment by hfcorriez** [comment]
Sorry, I am not sure what's your context code. so I can not emulate the test.
Can you give me you full environment settings?

**Comment by IngwiePhoenix** [comment]
Sure!

I use Workerman to create a multi-process TCP service. So the file in which php-childprocess is used, is within a sub-process. The code is here:

http://git.ingwie.me/ingwie/bird3/blob/cluster-vc+sticky/php-lib/YiiApp.php#L199

YiiApp::run() is called via an RPC mechanism called [hprose](https://github.com/hprose). I contact it from within NodeJS. As you see, I have a sandbox attached there that will run some code in a restricted environment. Also I want to avoid having to restart the worker over and over again, which for one point will have me lose all the request/connection and other stats and thus makes the app load slower. I was hoping that through php-childprocess I could possibly run the Yii based app in a child process, capture the output and send it back, without having to pollute the worker's process with a User's request (Cookies, POST/GET data, ...). Do you see what i mean? I am not a native english speaker, so maybe I am talking a little gibberish. :)

**Comment by hfcorriez** [comment]
It's OK, I see what's your mean. I must write some test case to test your envrionment. Is it very important for you? I am busy on moving the office to the new place. And some complex things in my company must  be done these days. So I think my testing will be work after some days. Is it OK? 
So, I am very sorry for that, I have not enough time handle this quickly.

**Comment by IngwiePhoenix** [comment]
That is fine with me, I am very patient. It is important but i am fine with waiting a little for you to finish what you need to do. Good luck with the moving :) If you have a solution, please let me know!

**Comment by hfcorriez** [comment]
I will tell you about my test work. thanks for your patience.

---

hfcorriez

在 2015年4月16日 星期四，14:49，Ingwie Phoenix 写道：

**Comment by hfcorriez** [comment]
I think I lose some code at some commits, I had fix it, you can use the latest code. ;)

If u had some thing else, Plz tell me.
